from application.test_suite import driver

from application.test_suite.modules import account
from application.test_suite.modules import application
from application.test_suite.modules import blocks
from application.test_suite.modules import collections
from application.test_suite.modules import direct_messages
from application.test_suite.modules import favorites
from application.test_suite.modules import followers
from application.test_suite.modules import friends
from application.test_suite.modules import friendships
from application.test_suite.modules import geo
from application.test_suite.modules import lists
from application.test_suite.modules import media
from application.test_suite.modules import mutes
from application.test_suite.modules import saved_searches
from application.test_suite.modules import statuses
from application.test_suite.modules import trends
from application.test_suite.modules import users
